# Base16 Generated
# Author: Flavours

$color0 = 0xff1c2736
$color1 = 0xff464e5a
$color2 = 0xff71767e
$color3 = 0xff9b9da2
$color4 = 0xffc6c5c7
$color5 = 0xfff0eceb
$color6 = 0xfff2efee
$color7 = 0xfff4f2f1
$color8 = 0xff53a4c0
$color9 = 0xffdacacf
$color10 = 0xffe1c5bf
$color11 = 0xffc1d8e9
$color12 = 0xffc1a39f
$color13 = 0xffceb4b4
$color14 = 0xff9e8186
$color15 = 0xffa9c2d5